<?php
# This file was automatically generated by the MediaWiki 1.39.9
# installer. If you make manual changes, please keep track in case you
# need to recreate them later.
#
# See docs/Configuration.md for all configurable settings
# and their default values, but don't forget to make changes in _this_
# file, not there.
#
# Further documentation for configuration settings may be found at:
# https://www.mediawiki.org/wiki/Manual:Configuration_settings

# Protect against web entry
if ( !defined( 'MEDIAWIKI' ) ) {
	exit;
}


## Uncomment this to disable output compression
# $wgDisableOutputCompression = true;

$wgSitename = "TestWiki";

## The URL base path to the directory containing the wiki;
## defaults for all runtime URL paths are based off of this.
## For more information on customizing the URLs
## (like /w/index.php/Page_title to /wiki/Page_title) please see:
## https://www.mediawiki.org/wiki/Manual:Short_URL
$wgScriptPath = "";

## The protocol and server name to use in fully-qualified URLs
$wgServer = "http://mediawiki.local:90";

## The URL path to static resources (images, scripts, etc.)
$wgResourceBasePath = $wgScriptPath;

## The URL paths to the logo.  Make sure you change this from the default,
## or else you'll overwrite your logo when you upgrade!
$wgLogos = [
	'1x' => "$wgResourceBasePath/resources/assets/change-your-logo.svg",
	'icon' => "$wgResourceBasePath/resources/assets/change-your-logo.svg",
];

## UPO means: this is also a user preference option

$wgEnableEmail = true;
$wgEnableUserEmail = true; # UPO

$wgEmergencyContact = "eguvenc@gmail.com";
$wgPasswordSender = "eguvenc@gmail.com";

$wgEnotifUserTalk = false; # UPO
$wgEnotifWatchlist = false; # UPO
$wgEmailAuthentication = true;

## Database settings
$wgDBtype = "mysql";
$wgDBserver = "localhost";
$wgDBname = "wikidb";
$wgDBuser = "admin";
$wgDBpassword = "Mbry8992@";

# MySQL specific settings
$wgDBprefix = "";

# MySQL table options to use during installation or update
$wgDBTableOptions = "ENGINE=InnoDB, DEFAULT CHARSET=binary";

# Shared database table
# This has no effect unless $wgSharedDB is also set.
$wgSharedTables[] = "actor";

## Shared memory settings
$wgMainCacheType = CACHE_ACCEL;
$wgMemCachedServers = [];

## To enable image uploads, make sure the 'images' directory
## is writable, then set this to true:
$wgEnableUploads = false;
#$wgUseImageMagick = true;
#$wgImageMagickConvertCommand = "/usr/bin/convert";

# InstantCommons allows wiki to use images from https://commons.wikimedia.org
$wgUseInstantCommons = false;

# Periodically send a pingback to https://www.mediawiki.org/ with basic data
# about this MediaWiki instance. The Wikimedia Foundation shares this data
# with MediaWiki developers to help guide future development efforts.
$wgPingback = true;

# Site language code, should be one of the list in ./includes/languages/data/Names.php
$wgLanguageCode = "en";

# Time zone
$wgLocaltimezone = "UTC";

## Set $wgCacheDirectory to a writable directory on the web server
## to make your wiki go slightly faster. The directory should not
## be publicly accessible from the web.
#$wgCacheDirectory = "$IP/cache";

$wgSecretKey = "e0d4f656c1918c3758fc0bd7b993883e9710f0547974a0240e1e462c4c27fce5";

# Changing this will log out all existing sessions.
$wgAuthenticationTokenVersion = "1";

# Site upgrade key. Must be set to a string (default provided) to turn on the
# web installer while LocalSettings.php is in place
$wgUpgradeKey = "7ad0f4c417f1e603";

## For attaching licensing metadata to pages, and displaying an
## appropriate copyright notice / icon. GNU Free Documentation
## License and Creative Commons licenses are supported so far.
$wgRightsPage = ""; # Set to the title of a wiki page that describes your license/copyright
$wgRightsUrl = "";
$wgRightsText = "";
$wgRightsIcon = "";

# Path to the GNU diff3 utility. Used for conflict resolution.
$wgDiff3 = "/usr/bin/diff3";

## Default skin: you can change the default skin. Use the internal symbolic
## names, e.g. 'vector' or 'monobook':
$wgDefaultSkin = "vector";

# Enabled skins.
# The following skins were automatically enabled:
wfLoadSkin( 'MinervaNeue' );
wfLoadSkin( 'MonoBook' );
wfLoadSkin( 'Timeless' );
wfLoadSkin( 'Vector' );

# ------------------------------------------------------------------------------------------------------------
# Wikibase Extension Start
# ------------------------------------------------------------------------------------------------------------

wfLoadExtension( 'WikibaseRepository', "$IP/extensions/Wikibase/extension-repo.json" );
require_once "$IP/extensions/Wikibase/repo/ExampleSettings.php";

wfLoadExtension( 'WikibaseClient', "$IP/extensions/Wikibase/extension-client.json" );
require_once "$IP/extensions/Wikibase/client/ExampleSettings.php";

$wgEnableWikibaseRepo = true;
$wgEnableWikibaseClient = true;

# Repo Settings
$wgWBRepoSettings['dataRightsUrl'] = "https://creativecommons.org/publicdomain/zero/1.0/";
$wgWBRepoSettings['siteGlobalID'] = 'test-wiki';

# Client Settings (To display repo)
$wgWBClientSettings['repoUrl'] = "http://mediawiki.local";
$wgWBClientSettings['repoScriptPath'] = "/w";  # Change according to MediaWiki installation
$wgWBClientSettings['repoDatabase'] = "wikidb";
$wgWBClientSettings['changesDatabase'] = "wikidb";

# ------------------------------------------------------------------------------------------------------------
# Wikibase Extension End
# ------------------------------------------------------------------------------------------------------------

# ------------------------------------------------------------------------------------------------------------
# PageForms Extension Start
# ------------------------------------------------------------------------------------------------------------

wfLoadExtension( 'PageForms' );

# ------------------------------------------------------------------------------------------------------------
# PageForms Extension End
# ------------------------------------------------------------------------------------------------------------

# ------------------------------------------------------------------------------------------------------------
# CirrusSearch + Elastica Extension Start
# ------------------------------------------------------------------------------------------------------------

wfLoadExtension( 'Elastica' );
wfLoadExtension( 'CirrusSearch' );

# Elasticsearch Server
$wgCirrusSearchServers = [ 'localhost' ];
$wgCirrusSearchClusters = [
    'default' => [ 'localhost' ]
];

# Additional Settings
$wgSearchType = 'CirrusSearch';
$wgCirrusSearchWikimediaExtraPlugin = true;
$wgCirrusSearchWikibaseIndexEntityData = true;
$wgCirrusSearchWikibaseEntityTypes = [
    'item' => true,
    'property' => true
];
# -----------------------
# Default Lang
# -----------------------
$wgLanguageCode = "en";

# ------------------------------------------------------------------------------------------------------------
# CirrusSearch + Elastica Extension End
# ------------------------------------------------------------------------------------------------------------


# If you are using Wikibase, additional settings may be needed
# e.g., to use forms for Wikibase entities and items


$wgShowExceptionDetails = true;
$wgDebugLogFile = "/var/www/mediawiki/error.log";

# End of automatically generated settings.
# Add more configuration options below.

